### ISSUE TITLE
Add atribute dat to wallpanel

### ISSUE THREAD

**Issue by LukaszP2** [Daanoz/ha-google-photos#15]
Can you show me how to add info from atribute to wallpanel?

**Comment by Daanoz** [comment]
You can display it using template variable on any card that supports it. For example:

```yaml
wallpanel:
  enabled: true
  image_url: media-entity://camera.google_photos_favorites_media
  cards:
    - type: markdown
      content: >-
        {{states.camera.google_photos_favorites_media.attributes.media_metadata.photo.cameraMake}},
        {{states.camera.google_photos_favorites_media.attributes.media_metadata.photo.cameraModel}}
```
