### ISSUE TITLE
Background Combos (2 in one)

### ISSUE THREAD

**Issue by Damienlee69** [Daanoz/ha-google-photos#3]
I have zero idea how possible it is, but it'd be cool to have the ability to use your albums as a background and/or screensaver.
Also, (I may have missed this), but, maybe the possibility to combine albums into one "slideshow". I know you can have multiple cards/multiple albums, but a combine line would be nice; use_album: album1, album 2. I dunno. Anyways, great work. Cheers.

**Comment by Daanoz** [comment]
With regards to the first question, that's hopefully coming very soon, coincidentally I created a PR today over at the [lovelace-wallpanel repository](https://github.com/j-a-n/lovelace-wallpanel/pull/84) doing exactly that!

For the second question, that's a bit more tricky since searching multiple albums is not natively supported by the [Google Photos api](https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search). I do [plan](https://github.com/Daanoz/ha-google-photos/blob/main/README.md#future-plans) to build some functionality to use more of the advanced search functionality that's available.

**Comment by Daanoz** [comment]
The maintainer of the [lovelace-wallpanel](https://github.com/j-a-n/lovelace-wallpanel) extension has merged my changes, so from version 4.8 onwards of that extension you can combine both!

Example
```yaml
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  image_url: media-entity://camera.google_photos_favorites_media
```
